version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2

    environment:
      GOOGLE_APPLICATION_CREDENTIALS: credentials/service-account.json

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: Restoring Cache - venv cache
          keys:
            - venv-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate

            pip install pip-tools
            make setup

      - run:
          name: prepare credentials
          command: |
            mkdir -p $(dirname $GOOGLE_APPLICATION_CREDENTIALS)
            echo $GCP_CREDENTIALS_GUMO_EXAMPLE_1d620b79fa32 > $GOOGLE_APPLICATION_CREDENTIALS

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - store_test_results:
          path: test-reports

      - save_cache:
          paths:
            - ./venv
          key: venv-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "requirements.txt" }}
